"""added Github Commits Table

Revision ID: 03130bb97217
Revises: aa505e75f382
Create Date: 2024-12-21 12:27:46.009341

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "03130bb97217"
down_revision: Union[str, None] = "aa505e75f382"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "github_commits",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("commit_hash", sa.String(), nullable=False),
        sa.Column("commit_author", sa.String(), nullable=False),
        sa.Column("commit_message", sa.String(), nullable=False),
        sa.Column("commit_date", sa.DateTime(), nullable=False),
        sa.Column("commit_summary", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("github_commits")
    # ### end Alembic commands ###
