"""last synced added to repo embedding

Revision ID: 10de8f654857
Revises: a1cf0fbdd858
Create Date: 2025-01-04 19:21:20.025442

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "10de8f654857"
down_revision: Union[str, None] = "a1cf0fbdd858"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "repo_embeddings", sa.Column("last_synced", sa.DateTime(), nullable=True)
    )
    op.drop_column("repo_embeddings", "lasy_synced")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "repo_embeddings",
        sa.Column(
            "lasy_synced", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("repo_embeddings", "last_synced")
    # ### end Alembic commands ###
