"""updated commit_summary type

Revision ID: 66af900f1a32
Revises: c9d580537903
Create Date: 2024-12-23 11:29:59.186757

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "66af900f1a32"
down_revision: Union[str, None] = "c9d580537903"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE github_commits
        ALTER COLUMN commit_summary
        TYPE JSON
        USING commit_summary::json
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE github_commits
        ALTER COLUMN commit_summary
        TYPE VARCHAR
        USING commit_summary::text
    """
    )
