"""create project & update txn table

Revision ID: 9dce5c6878a6
Revises: 22907d47cc67
Create Date: 2024-12-16 15:26:27.773558

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9dce5c6878a6"
down_revision: Union[str, None] = "22907d47cc67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "txns",
        "txn_type",
        existing_type=postgresql.ENUM(
            "credit_purchase", "canceled", "refund", "bonus", name="txntype"
        ),
        nullable=True,
        existing_server_default=sa.text("'credit_purchase'::txntype"),
    )
    op.alter_column(
        "users", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "id", existing_type=sa.INTEGER(), nullable=True, autoincrement=True
    )
    op.alter_column(
        "txns",
        "txn_type",
        existing_type=postgresql.ENUM(
            "credit_purchase", "canceled", "refund", "bonus", name="txntype"
        ),
        nullable=False,
        existing_server_default=sa.text("'credit_purchase'::txntype"),
    )
    # ### end Alembic commands ###
