"""last synced added to repo embedding

Revision ID: a1cf0fbdd858
Revises: b23b979e38b3
Create Date: 2025-01-04 19:19:09.065703

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a1cf0fbdd858"
down_revision: Union[str, None] = "b23b979e38b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "repo_embeddings", sa.Column("lasy_synced", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("repo_embeddings", "lasy_synced")
    # ### end Alembic commands ###
