"""added avatar url

Revision ID: c9d580537903
Revises: 03130bb97217
Create Date: 2024-12-21 16:03:57.791372

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c9d580537903"
down_revision: Union[str, None] = "03130bb97217"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "github_commits", sa.Column("commit_avatar_url", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("github_commits", "commit_avatar_url")
    # ### end Alembic commands ###
