"""testing Vector db

Revision ID: e6140cf7389c
Revises: d3d06e0b132a
Create Date: 2024-12-29 00:42:40.994438

"""

from typing import Sequence, Union
from app.models.repo_embeddings import Vector
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e6140cf7389c"
down_revision: Union[str, None] = "d3d06e0b132a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vector_db_test",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vector", Vector(100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("items")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "items",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("embedding", sa.NullType(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="items_pkey"),
    )
    op.drop_table("vector_db_test")
    # ### end Alembic commands ###
