"""created repo embeddings table

Revision ID: e7aea48799cb
Revises: e6140cf7389c
Create Date: 2024-12-29 01:05:56.992585

"""

from typing import Sequence, Union
from app.models.repo_embeddings import Vector
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e7aea48799cb"
down_revision: Union[str, None] = "e6140cf7389c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repo_embeddings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repo_url", sa.String(), nullable=False),
        sa.Column("summary_embedding", Vector(768), nullable=True),
        sa.Column("source_code", sa.String(), nullable=True),
        sa.Column("file_name", sa.String(), nullable=True),
        sa.Column("summary", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_repo_embeddings_summary_embedding"),
        "repo_embeddings",
        ["summary_embedding"],
        unique=False,
    )
    op.create_table(
        "repo_embeddings_projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repo_embeddings_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repo_embeddings_id"],
            ["repo_embeddings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("vector_db_test")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vector_db_test",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("vector", sa.NullType(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="vector_db_test_pkey"),
    )
    op.drop_table("repo_embeddings_projects")
    op.drop_index(
        op.f("ix_repo_embeddings_summary_embedding"), table_name="repo_embeddings"
    )
    op.drop_table("repo_embeddings")
    # ### end Alembic commands ###
